// <auto-generated />
namespace Ghsaa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new5));
        
        string IMigrationMetadata.Id
        {
            get { return "201607152102118_new5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
